# Generated by Django 5.1.4 on 2025-01-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_cron', '0005_remove_cronjoblog_idx_code_success_ran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('cronjoblog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_cron.cronjoblog')),
            ],
            bases=('django_cron.cronjoblog',),
        ),
    ]
