# Generated by Django 5.1.4 on 2025-01-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cron', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cronjoblog',
            table='custom_cron_cronjoblog',
        ),
    ]
